name: Publish to NPM 

on: 
  pull_request:
    branches: [ production ]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo ${GITHUB_CONTEXT} 
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
      #    registry-url: 'https://registry.npmjs.org'
      #- run: yarn publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
    